name: Deploy Documentation

on:
  push:
    branches: [ myoassist0.1prepare ]
  pull_request:
    branches: [ myoassist0.1prepare ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: myoassist0.1prepare
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser
    
    - name: Setup Sphinx documentation
      run: |
        # Create Sphinx documentation structure
        mkdir -p sphinx-docs
        
        # Copy Sphinx configuration and source files from gh-pages branch
        git fetch origin gh-pages
        git checkout origin/gh-pages -- conf.py index.rst install.rst tutorials.rst models.rst modeling.rst rl_imitation_tutorial.rst rl_get_observation.rst rl_terrain_tutorial.rst controllers.rst optimization.rst processing.rst running_simulations.rst running_optimizations.rst understanding_cost.rst exoskeleton_controllers.rst processing_results.rst rl_analyze_tutorial.rst publications.rst Makefile
        
        # Move files to sphinx-docs directory
        mv conf.py index.rst install.rst tutorials.rst models.rst modeling.rst rl_imitation_tutorial.rst rl_get_observation.rst rl_terrain_tutorial.rst controllers.rst optimization.rst processing.rst running_simulations.rst running_optimizations.rst understanding_cost.rst exoskeleton_controllers.rst processing_results.rst rl_analyze_tutorial.rst publications.rst Makefile sphinx-docs/
        
        # Copy documentation source files to parent directory so ../docs/ includes work
        if [ -d "docs" ]; then
          echo "Copying documentation source files..."
          cp -r docs sphinx-docs/../
        fi
        
        echo "Sphinx documentation structure created:"
        ls -la sphinx-docs/
        echo "Docs directory contents:"
        ls -la sphinx-docs/../docs/ || echo "No docs directory found"
    
    - name: Build Sphinx documentation
      run: |
        cd sphinx-docs
        
        # Build the documentation
        make html
        
        # Copy built documentation to docs-site
        mkdir -p ../docs-site
        cp -r _build/html/* ../docs-site/
        
        echo "Sphinx documentation built successfully"
        ls -la ../docs-site/
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs-site
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 