name: Deploy Documentation

on:
  push:
    branches: [ myoassist0.1prepare ]
  pull_request:
    branches: [ myoassist0.1prepare ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: myoassist0.1prepare
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme myst-parser
    
    - name: Create documentation structure
      run: |
        # Create a simple documentation structure
        mkdir -p docs-site
        cp docs/*.md docs-site/ 2>/dev/null || true
        cp docs/*.ipynb docs-site/ 2>/dev/null || true
        cp -r docs/assets docs-site/ 2>/dev/null || true
        cp -r docs/images docs-site/ 2>/dev/null || true
        
        # Create a simple index.html if it doesn't exist
        if [ ! -f docs-site/index.html ]; then
          cat > docs-site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>MyoAssist Documentation</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
              <style>
                body { padding-top: 2rem; }
                .hero { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 4rem 0; }
              </style>
          </head>
          <body>
              <div class="hero">
                  <div class="container text-center">
                      <h1>MyoAssist Documentation</h1>
                      <p class="lead">A Python-based framework for optimizing neuromuscular reflex controllers</p>
                  </div>
              </div>
              <div class="container mt-5">
                  <h2>Documentation</h2>
                  <div class="row">
                      <div class="col-md-6">
                          <h3>Getting Started</h3>
                          <ul>
                              <li><a href="Running_Simulations.md">Running Simulations</a></li>
                              <li><a href="Running_Optimizations.md">Running Optimizations</a></li>
                              <li><a href="Understanding_Cost.md">Understanding Cost Functions</a></li>
                          </ul>
                      </div>
                      <div class="col-md-6">
                          <h3>Advanced Topics</h3>
                          <ul>
                              <li><a href="Exoskeleton_Controllers.md">Exoskeleton Controllers</a></li>
                              <li><a href="Processing_Results.md">Processing Results</a></li>
                              <li><a href="Modeling.md">Modeling</a></li>
                          </ul>
                      </div>
                  </div>
                  <h3>Tutorials</h3>
                  <ul>
                      <li><a href="exo_tutorial.ipynb">Exoskeleton Tutorial</a></li>
                      <li><a href="rl_tutorial.ipynb">Reinforcement Learning Tutorial</a></li>
                  </ul>
              </div>
          </body>
          </html>
          EOF
        fi
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/myoassist0.1prepare'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site
        force_orphan: true 